<?php

/**
 * Admin sidebar menu — مصدر واحد للتنظيم والأيقونات.
 * active: أنماط routeIs (string أو array)
 */
return [
    [
        'type' => 'link',
        'label' => 'لوحة التحكم',
        'route' => 'admin.dashboard',
        'icon' => 'fe fe-grid',
        'color' => 'primary',
        'active' => 'admin.dashboard',
    ],
    [
        'type' => 'external',
        'label' => 'الواجهة الأمامية',
        'url' => '/',
        'icon' => 'fe fe-globe',
        'color' => 'success',
    ],
    [
        'type' => 'group',
        'label' => 'العملاء',
        'icon' => 'fe fe-users',
        'color' => 'info',
        'active' => ['admin.customers.*'],
        'children' => [
            ['type' => 'link', 'label' => 'قائمة العملاء', 'route' => 'admin.customers.index', 'icon' => 'fe fe-users', 'color' => 'info', 'active' => 'admin.customers.*'],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'المنتجات',
        'icon' => 'fe fe-package',
        'color' => 'success',
        'active' => ['admin.products.*', 'admin.order-requests.*'],
        'children' => [
            ['type' => 'link', 'label' => 'المنتجات', 'route' => 'admin.products.index', 'icon' => 'fe fe-package', 'color' => 'success', 'active' => ['admin.products.index', 'admin.products.show', 'admin.products.edit']],
            ['type' => 'link', 'label' => 'إضافة منتج', 'route' => 'admin.products.create', 'icon' => 'fe fe-plus-circle', 'color' => 'success', 'active' => 'admin.products.create'],
            ['type' => 'link', 'label' => 'طلبات الباقات', 'route' => 'admin.order-requests.index', 'icon' => 'fe fe-shopping-cart', 'color' => 'warning', 'active' => 'admin.order-requests.*'],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'الخدمات',
        'icon' => 'fe fe-layers',
        'color' => 'teal',
        'active' => ['admin.service-types.*', 'admin.offered-services.*', 'admin.customer-services.*'],
        'children' => [
            ['type' => 'link', 'label' => 'أنواع الخدمات', 'route' => 'admin.service-types.index', 'icon' => 'fe fe-tag', 'color' => 'secondary', 'active' => 'admin.service-types.*'],
            ['type' => 'link', 'label' => 'الخدمات المعروضة', 'route' => 'admin.offered-services.index', 'icon' => 'fe fe-layers', 'color' => 'primary', 'active' => ['admin.offered-services.index', 'admin.offered-services.show', 'admin.offered-services.edit']],
            ['type' => 'link', 'label' => 'خدمات العملاء', 'route' => 'admin.customer-services.index', 'icon' => 'fe fe-briefcase', 'color' => 'teal', 'active' => ['admin.customer-services.index', 'admin.customer-services.show', 'admin.customer-services.edit']],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'المالية',
        'icon' => 'fe fe-dollar-sign',
        'color' => 'warning',
        'active' => ['admin.invoices.*', 'admin.payments.*'],
        'children' => [
            ['type' => 'link', 'label' => 'الفواتير', 'route' => 'admin.invoices.index', 'icon' => 'fe fe-file-text', 'color' => 'warning', 'active' => ['admin.invoices.index', 'admin.invoices.show', 'admin.invoices.edit']],
            ['type' => 'link', 'label' => 'إنشاء فاتورة', 'route' => 'admin.invoices.create', 'icon' => 'fe fe-file-plus', 'color' => 'warning', 'active' => 'admin.invoices.create'],
            ['type' => 'link', 'label' => 'المدفوعات', 'route' => 'admin.payments.index', 'icon' => 'fe fe-credit-card', 'color' => 'success', 'active' => ['admin.payments.index', 'admin.payments.show']],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'الدعم الفني',
        'icon' => 'fe fe-message-circle',
        'color' => 'primary',
        'active' => ['admin.tickets.*'],
        'children' => [
            ['type' => 'link', 'label' => 'التذاكر', 'route' => 'admin.tickets.index', 'icon' => 'fe fe-message-circle', 'color' => 'info', 'active' => ['admin.tickets.index', 'admin.tickets.show', 'admin.tickets.edit']],
            ['type' => 'link', 'label' => 'تذكرة جديدة', 'route' => 'admin.tickets.create', 'icon' => 'fe fe-plus', 'color' => 'info', 'active' => 'admin.tickets.create'],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'المدونة',
        'icon' => 'fe fe-book-open',
        'color' => 'primary',
        'active' => ['admin.blog.*'],
        'children' => [
            ['type' => 'link', 'label' => 'المقالات', 'route' => 'admin.blog.posts.index', 'icon' => 'fe fe-book-open', 'color' => 'primary', 'active' => 'admin.blog.posts.*'],
            ['type' => 'link', 'label' => 'مقال بالذكاء الاصطناعي', 'route' => 'admin.blog.ai-posts.create', 'icon' => 'fe fe-cpu', 'color' => 'purple', 'active' => 'admin.blog.ai-posts.*'],
            ['type' => 'link', 'label' => 'التصنيفات', 'route' => 'admin.blog.categories.index', 'icon' => 'fe fe-folder', 'color' => 'secondary', 'active' => 'admin.blog.categories.*'],
            ['type' => 'link', 'label' => 'الوسوم', 'route' => 'admin.blog.tags.index', 'icon' => 'fe fe-hash', 'color' => 'secondary', 'active' => 'admin.blog.tags.*'],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'Evolution API',
        'icon' => 'fe fe-message-square',
        'color' => 'success',
        'active' => ['admin.whatsapp*', 'admin.evolution-api.*'],
        'children' => [
            ['type' => 'link', 'label' => 'الرسائل', 'route' => 'admin.whatsapp-messages.index', 'icon' => 'fe fe-message-square', 'color' => 'success', 'active' => 'admin.whatsapp-messages.*'],
            ['type' => 'link', 'label' => 'إعدادات واتساب', 'route' => 'admin.whatsapp-settings.index', 'icon' => 'fe fe-settings', 'color' => 'success', 'active' => 'admin.whatsapp-settings.*'],
            ['type' => 'link', 'label' => 'إعدادات Evolution', 'route' => 'admin.evolution-api.settings.index', 'icon' => 'fe fe-sliders', 'color' => 'teal', 'active' => 'admin.evolution-api.settings.*'],
            ['type' => 'link', 'label' => 'Instances', 'route' => 'admin.evolution-api.instances.index', 'icon' => 'fe fe-smartphone', 'color' => 'teal', 'active' => 'admin.evolution-api.instances.*'],
            ['type' => 'link', 'label' => 'إرسال', 'route' => 'admin.evolution-api.send.text', 'icon' => 'fe fe-send', 'color' => 'teal', 'active' => 'admin.evolution-api.send.*'],
            ['type' => 'link', 'label' => 'المجموعات', 'route' => 'admin.evolution-api.groups.index', 'icon' => 'fe fe-users', 'color' => 'teal', 'active' => ['admin.evolution-api.groups.*'], 'active_exclude' => ['admin.evolution-api.groups.compare*']],
            ['type' => 'link', 'label' => 'مقارنة WA', 'route' => 'admin.evolution-api.groups.compare', 'icon' => 'fe fe-git-merge', 'color' => 'teal', 'active' => 'admin.evolution-api.groups.compare*'],
            ['type' => 'link', 'label' => 'جهات الاتصال', 'route' => 'admin.evolution-api.contacts.index', 'icon' => 'fe fe-book', 'color' => 'teal', 'active' => 'admin.evolution-api.contacts.*'],
            ['type' => 'link', 'label' => 'Webhook', 'route' => 'admin.evolution-api.webhook.index', 'icon' => 'fe fe-link', 'color' => 'teal', 'active' => 'admin.evolution-api.webhook.*'],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'التقارير',
        'icon' => 'fe fe-bar-chart-2',
        'color' => 'danger',
        'active' => 'admin.reports.*',
        'children' => [
            ['type' => 'link', 'label' => 'لوحة التقارير', 'route' => 'admin.reports.index', 'icon' => 'fe fe-pie-chart', 'color' => 'danger', 'active' => 'admin.reports.index'],
            ['type' => 'category', 'label' => 'تقارير تفصيلية'],
            ['type' => 'link', 'label' => 'تقرير العملاء', 'route' => 'admin.reports.customers', 'icon' => 'fe fe-users', 'color' => 'info', 'active' => 'admin.reports.customers'],
            ['type' => 'link', 'label' => 'تقرير الفواتير', 'route' => 'admin.reports.invoices', 'icon' => 'fe fe-file-text', 'color' => 'warning', 'active' => 'admin.reports.invoices'],
            ['type' => 'link', 'label' => 'تقرير المنتجات', 'route' => 'admin.reports.products', 'icon' => 'fe fe-package', 'color' => 'success', 'active' => 'admin.reports.products'],
            ['type' => 'link', 'label' => 'تقرير التذاكر', 'route' => 'admin.reports.tickets', 'icon' => 'fe fe-message-circle', 'color' => 'primary', 'active' => 'admin.reports.tickets'],
            ['type' => 'category', 'label' => 'تصدير'],
            ['type' => 'link', 'label' => 'تصدير العملاء', 'route' => 'admin.reports.export.customers', 'icon' => 'fe fe-download', 'color' => 'secondary', 'active' => null],
            ['type' => 'link', 'label' => 'تصدير الفواتير', 'route' => 'admin.reports.export.invoices', 'icon' => 'fe fe-download', 'color' => 'secondary', 'active' => null],
            ['type' => 'link', 'label' => 'تصدير المنتجات', 'route' => 'admin.reports.export.products', 'icon' => 'fe fe-download', 'color' => 'secondary', 'active' => null],
            ['type' => 'link', 'label' => 'تصدير التذاكر', 'route' => 'admin.reports.export.tickets', 'icon' => 'fe fe-download', 'color' => 'secondary', 'active' => null],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'الاستضافة والسيرفرات',
        'icon' => 'fe fe-server',
        'color' => 'teal',
        'active' => ['admin.coolify.*', 'admin.whm.*', 'admin.cyberpanel.*', 'admin.infrastructure.*'],
        'children' => [
            [
                'type' => 'subgroup',
                'label' => 'VPS / البنية',
                'icon' => 'fe fe-hard-drive',
                'color' => 'teal',
                'active' => ['admin.infrastructure.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'سيرفرات VPS', 'route' => 'admin.infrastructure.servers.index', 'icon' => 'fe fe-hard-drive', 'color' => 'teal', 'active' => 'admin.infrastructure.servers.*'],
                    ['type' => 'link', 'label' => 'إعدادات مزودي VPS', 'route' => 'admin.infrastructure.settings.index', 'icon' => 'fe fe-sliders', 'color' => 'secondary', 'active' => 'admin.infrastructure.settings.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'Coolify — لوحة التشغيل',
                'icon' => 'fe fe-activity',
                'color' => 'teal',
                'active' => [
                    'admin.coolify.overview',
                    'admin.coolify.operations.*',
                    'admin.coolify.readiness.*',
                    'admin.coolify.resources.*',
                ],
                'children' => [
                    ['type' => 'link', 'label' => 'لوحة Coolify', 'route' => 'admin.coolify.overview', 'icon' => 'fe fe-activity', 'color' => 'teal', 'active' => 'admin.coolify.overview'],
                    ['type' => 'link', 'label' => 'مركز العمليات', 'route' => 'admin.coolify.operations.index', 'icon' => 'fe fe-alert-circle', 'color' => 'danger', 'active' => 'admin.coolify.operations.*'],
                    ['type' => 'link', 'label' => 'جاهزية الاستضافة', 'route' => 'admin.coolify.readiness.index', 'icon' => 'fe fe-check-circle', 'color' => 'success', 'active' => 'admin.coolify.readiness.*'],
                    ['type' => 'link', 'label' => 'كل الموارد', 'route' => 'admin.coolify.resources.index', 'icon' => 'fe fe-grid', 'color' => 'primary', 'active' => 'admin.coolify.resources.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'Coolify — الموارد',
                'icon' => 'fe fe-server',
                'color' => 'primary',
                'active' => [
                    'admin.coolify.servers.*',
                    'admin.coolify.projects.*',
                    'admin.coolify.applications.*',
                    'admin.coolify.services.*',
                    'admin.coolify.databases.*',
                    'admin.coolify.deployments.*',
                ],
                'children' => [
                    ['type' => 'link', 'label' => 'السيرفرات', 'route' => 'admin.coolify.servers.index', 'icon' => 'fe fe-server', 'color' => 'primary', 'active' => ['admin.coolify.servers.index', 'admin.coolify.servers.show', 'admin.coolify.servers.edit']],
                    ['type' => 'link', 'label' => 'المشاريع', 'route' => 'admin.coolify.projects.index', 'icon' => 'fe fe-layers', 'color' => 'info', 'active' => ['admin.coolify.projects.index', 'admin.coolify.projects.show', 'admin.coolify.projects.edit']],
                    ['type' => 'link', 'label' => 'التطبيقات', 'route' => 'admin.coolify.applications.index', 'icon' => 'fe fe-box', 'color' => 'purple', 'active' => 'admin.coolify.applications.*'],
                    ['type' => 'link', 'label' => 'الخدمات', 'route' => 'admin.coolify.services.index', 'icon' => 'fe fe-grid', 'color' => 'secondary', 'active' => 'admin.coolify.services.*'],
                    ['type' => 'link', 'label' => 'قواعد البيانات', 'route' => 'admin.coolify.databases.index', 'icon' => 'fe fe-database', 'color' => 'warning', 'active' => 'admin.coolify.databases.*'],
                    ['type' => 'link', 'label' => 'النشرات', 'route' => 'admin.coolify.deployments.index', 'icon' => 'fe fe-upload-cloud', 'color' => 'danger', 'active' => 'admin.coolify.deployments.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'Coolify — النسخ',
                'icon' => 'fe fe-archive',
                'color' => 'warning',
                'active' => ['admin.coolify.backups.*', 'admin.coolify.private-keys.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'مركز النسخ', 'route' => 'admin.coolify.backups.index', 'icon' => 'fe fe-archive', 'color' => 'warning', 'active' => 'admin.coolify.backups.*'],
                    ['type' => 'link', 'label' => 'مفاتيح SSH', 'route' => 'admin.coolify.private-keys.index', 'icon' => 'fe fe-lock', 'color' => 'secondary', 'active' => 'admin.coolify.private-keys.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'Coolify — WordPress & كتالوج',
                'icon' => 'fab fa-wordpress',
                'color' => 'info',
                'active' => ['admin.coolify.wordpress-sites.*', 'admin.coolify.catalog.*', 'admin.coolify.catalog-settings.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'مواقع WordPress', 'route' => 'admin.coolify.wordpress-sites.index', 'icon' => 'fab fa-wordpress', 'color' => 'info', 'active' => 'admin.coolify.wordpress-sites.*'],
                    ['type' => 'link', 'label' => 'كتالوج الموارد', 'route' => 'admin.coolify.catalog.index', 'icon' => 'fe fe-package', 'color' => 'success', 'active' => ['admin.coolify.catalog.index', 'admin.coolify.catalog.show']],
                    ['type' => 'link', 'label' => 'إعدادات الكتالوج', 'route' => 'admin.coolify.catalog-settings.index', 'icon' => 'fe fe-sliders', 'color' => 'secondary', 'active' => 'admin.coolify.catalog-settings.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'Coolify — التكاملات',
                'icon' => 'fe fe-link',
                'color' => 'secondary',
                'active' => [
                    'admin.coolify.github-apps.*',
                    'admin.coolify.cloud-tokens.*',
                    'admin.coolify.hetzner.*',
                    'admin.coolify.teams.*',
                    'admin.coolify.settings.*',
                ],
                'children' => [
                    ['type' => 'link', 'label' => 'GitHub Apps', 'route' => 'admin.coolify.github-apps.index', 'icon' => 'fab fa-github', 'color' => 'secondary', 'active' => 'admin.coolify.github-apps.*'],
                    ['type' => 'link', 'label' => 'Cloud Tokens', 'route' => 'admin.coolify.cloud-tokens.index', 'icon' => 'fe fe-lock', 'color' => 'info', 'active' => 'admin.coolify.cloud-tokens.*'],
                    ['type' => 'link', 'label' => 'Hetzner', 'route' => 'admin.coolify.hetzner.index', 'icon' => 'fe fe-cloud', 'color' => 'primary', 'active' => 'admin.coolify.hetzner.*'],
                    ['type' => 'link', 'label' => 'فرق العمل', 'route' => 'admin.coolify.teams.index', 'icon' => 'fe fe-users', 'color' => 'teal', 'active' => 'admin.coolify.teams.*'],
                    ['type' => 'link', 'label' => 'إعدادات Coolify', 'route' => 'admin.coolify.settings.index', 'icon' => 'fe fe-settings', 'color' => 'warning', 'active' => 'admin.coolify.settings.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'WHM / cPanel',
                'icon' => 'fe fe-monitor',
                'color' => 'info',
                'active' => ['admin.whm.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'إعدادات WHM', 'route' => 'admin.whm.settings.index', 'icon' => 'fe fe-settings', 'color' => 'info', 'active' => 'admin.whm.settings.*'],
                    ['type' => 'link', 'label' => 'حالة السيرفر', 'route' => 'admin.whm.server.index', 'icon' => 'fe fe-monitor', 'color' => 'teal', 'active' => 'admin.whm.server.*'],
                    ['type' => 'link', 'label' => 'حسابات الاستضافة', 'route' => 'admin.whm.accounts.index', 'icon' => 'fe fe-user-check', 'color' => 'success', 'active' => 'admin.whm.accounts.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'CyberPanel',
                'icon' => 'fe fe-server',
                'color' => 'purple',
                'active' => ['admin.cyberpanel.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'إعدادات CyberPanel', 'route' => 'admin.cyberpanel.settings.index', 'icon' => 'fe fe-settings', 'color' => 'purple', 'active' => 'admin.cyberpanel.settings.*'],
                    ['type' => 'link', 'label' => 'مواقع الاستضافة', 'route' => 'admin.cyberpanel.websites.index', 'icon' => 'fe fe-globe', 'color' => 'success', 'active' => 'admin.cyberpanel.websites.*'],
                    ['type' => 'link', 'label' => 'الباقات', 'route' => 'admin.cyberpanel.packages.index', 'icon' => 'fe fe-package', 'color' => 'info', 'active' => 'admin.cyberpanel.packages.*'],
                    ['type' => 'link', 'label' => 'WordPress', 'route' => 'admin.cyberpanel.wordpress-sites.index', 'icon' => 'fab fa-wordpress', 'color' => 'primary', 'active' => 'admin.cyberpanel.wordpress-sites.*'],
                ],
            ],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'النطاقات',
        'icon' => 'fe fe-link-2',
        'color' => 'purple',
        'active' => ['admin.domains.*', 'admin.cloudflare.*', 'admin.namecom.*'],
        'children' => [
            ['type' => 'category', 'label' => 'مركز النطاقات'],
            ['type' => 'link', 'label' => 'مركز التحكم', 'route' => 'admin.domains.index', 'icon' => 'fe fe-globe', 'color' => 'purple', 'active' => 'admin.domains.index'],
            ['type' => 'link', 'label' => 'البحث عن نطاق', 'route' => 'admin.domains.search', 'icon' => 'fe fe-search', 'color' => 'info', 'active' => 'admin.domains.search'],
            ['type' => 'link', 'label' => 'فوترة النطاقات', 'route' => 'admin.domains.settings.index', 'icon' => 'fe fe-dollar-sign', 'color' => 'warning', 'active' => 'admin.domains.settings.*'],
            ['type' => 'category', 'label' => 'Cloudflare'],
            ['type' => 'link', 'label' => 'Zones', 'route' => 'admin.cloudflare.zones.index', 'icon' => 'fe fe-cloud', 'color' => 'warning', 'active' => 'admin.cloudflare.zones.*'],
            ['type' => 'link', 'label' => 'Registrar', 'route' => 'admin.cloudflare.registrar.index', 'icon' => 'fe fe-shopping-bag', 'color' => 'warning', 'active' => 'admin.cloudflare.registrar.*'],
            ['type' => 'link', 'label' => 'إعدادات Cloudflare', 'route' => 'admin.cloudflare.settings.index', 'icon' => 'fe fe-settings', 'color' => 'secondary', 'active' => 'admin.cloudflare.settings.*'],
            ['type' => 'category', 'label' => 'name.com'],
            ['type' => 'link', 'label' => 'نطاقات name.com', 'route' => 'admin.namecom.domains.index', 'icon' => 'fe fe-link', 'color' => 'purple', 'active' => 'admin.namecom.domains.*'],
            ['type' => 'link', 'label' => 'إعدادات name.com', 'route' => 'admin.namecom.settings.index', 'icon' => 'fe fe-settings', 'color' => 'secondary', 'active' => 'admin.namecom.settings.*'],
        ],
    ],
    [
        'type' => 'group',
        'label' => 'النظام والإعدادات',
        'icon' => 'fe fe-settings',
        'color' => 'secondary',
        'active' => [
            'users.*', 'roles.*', 'admin.settings.*', 'admin.settings.email.*', 'admin.settings.password-reset-message.*', 'admin.settings.phone-otp.*', 'admin.mail-templates.*',
            'admin.homepage.hero.*', 'admin.homepage.seo.*', 'admin.storage.*', 'admin.backups.*',
            'admin.backup-schedules.*', 'admin.backup-storage.*', 'admin.storage-disk-mappings.*',
            'admin.ai.*', 'admin.system-database.*',
        ],
        'children' => [
            [
                'type' => 'subgroup',
                'label' => 'عام',
                'icon' => 'fe fe-sliders',
                'color' => 'secondary',
                'active' => [
                    'admin.settings.*',
                    'admin.mail-templates.*',
                    'admin.homepage.hero.*',
                    'admin.homepage.seo.*',
                    'admin.system-database.*',
                ],
                'children' => [
                    [
                        'type' => 'link',
                        'label' => 'إعدادات الموقع',
                        'route' => 'admin.settings.index',
                        'icon' => 'fe fe-settings',
                        'color' => 'secondary',
                        'active' => 'admin.settings.*',
                        'active_exclude' => [
                            'admin.settings.email.*',
                            'admin.settings.password-reset-message.*',
                            'admin.settings.phone-otp.*',
                        ],
                    ],
                    ['type' => 'link', 'label' => 'SMTP', 'route' => 'admin.settings.email.index', 'icon' => 'fe fe-mail', 'color' => 'info', 'active' => 'admin.settings.email.*'],
                    ['type' => 'link', 'label' => 'قوالب البريد', 'route' => 'admin.mail-templates.index', 'icon' => 'fe fe-file-text', 'color' => 'info', 'active' => 'admin.mail-templates.*'],
                    ['type' => 'link', 'label' => 'رسالة استعادة كلمة المرور', 'route' => 'admin.settings.password-reset-message.edit', 'icon' => 'fe fe-lock', 'color' => 'warning', 'active' => 'admin.settings.password-reset-message.*'],
                    ['type' => 'link', 'label' => 'إعدادات OTP واتساب', 'route' => 'admin.settings.phone-otp.edit', 'icon' => 'fe fe-smartphone', 'color' => 'success', 'active' => 'admin.settings.phone-otp.*'],
                    ['type' => 'link', 'label' => 'الهيرو', 'route' => 'admin.homepage.hero.index', 'icon' => 'fe fe-image', 'color' => 'primary', 'active' => 'admin.homepage.hero.*'],
                    ['type' => 'link', 'label' => 'SEO', 'route' => 'admin.homepage.seo.index', 'icon' => 'fe fe-search', 'color' => 'success', 'active' => 'admin.homepage.seo.*'],
                    ['type' => 'link', 'label' => 'قاعدة بيانات النظام', 'route' => 'admin.system-database.index', 'icon' => 'fe fe-database', 'color' => 'danger', 'active' => 'admin.system-database.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'المستخدمون والصلاحيات',
                'icon' => 'fe fe-users',
                'color' => 'primary',
                'active' => ['users.*', 'roles.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'المستخدمون', 'route' => 'users.index', 'icon' => 'fe fe-user', 'color' => 'primary', 'active' => ['users.index', 'users.show', 'users.edit']],
                    ['type' => 'link', 'label' => 'إضافة مستخدم', 'route' => 'users.create', 'icon' => 'fe fe-user-plus', 'color' => 'primary', 'active' => 'users.create'],
                    ['type' => 'link', 'label' => 'الصلاحيات', 'route' => 'roles.index', 'icon' => 'fe fe-shield', 'color' => 'danger', 'active' => ['roles.index', 'roles.show', 'roles.edit']],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'التخزين والنسخ',
                'icon' => 'fe fe-cloud',
                'color' => 'info',
                'active' => [
                    'admin.storage.*',
                    'admin.backups.*',
                    'admin.backup-schedules.*',
                    'admin.backup-storage.*',
                    'admin.storage-disk-mappings.*',
                ],
                'children' => [
                    ['type' => 'link', 'label' => 'أماكن التخزين', 'route' => 'admin.storage.index', 'icon' => 'fe fe-cloud', 'color' => 'info', 'active' => ['admin.storage.index', 'admin.storage.show', 'admin.storage.edit']],
                    ['type' => 'link', 'label' => 'إحصائيات التخزين', 'route' => 'admin.storage.analytics', 'icon' => 'fe fe-bar-chart', 'color' => 'secondary', 'active' => 'admin.storage.analytics'],
                    ['type' => 'link', 'label' => 'نسخ Laravel', 'route' => 'admin.backups.index', 'icon' => 'fe fe-archive', 'color' => 'warning', 'active' => ['admin.backups.index', 'admin.backups.show']],
                    ['type' => 'link', 'label' => 'جداول النسخ', 'route' => 'admin.backup-schedules.index', 'icon' => 'fe fe-calendar', 'color' => 'warning', 'active' => 'admin.backup-schedules.*'],
                ],
            ],
            [
                'type' => 'subgroup',
                'label' => 'الذكاء الاصطناعي',
                'icon' => 'fe fe-cpu',
                'color' => 'purple',
                'active' => ['admin.ai.*'],
                'children' => [
                    ['type' => 'link', 'label' => 'نماذج AI', 'route' => 'admin.ai.models.index', 'icon' => 'fe fe-cpu', 'color' => 'purple', 'active' => 'admin.ai.models.*'],
                    ['type' => 'link', 'label' => 'إعدادات AI', 'route' => 'admin.ai.settings.index', 'icon' => 'fe fe-sliders', 'color' => 'purple', 'active' => 'admin.ai.settings.*'],
                ],
            ],
        ],
    ],
    [
        'type' => 'link',
        'label' => 'الملف الشخصي',
        'route' => 'profile.show',
        'icon' => 'fe fe-user',
        'color' => 'pink',
        'active' => 'profile.*',
    ],
];
