<?php

/**
 * كتالوج موارد Coolify الافتراضي — يُدمج مع جدول coolify_catalog_items (DB يغلّب نفس slug).
 */
return [
    /** مصدر قوالب one-click الرسمية من مشروع Coolify (للمزامنة عند غياب GET /services/types). */
    'service_templates_url' => env(
        'COOLIFY_SERVICE_TEMPLATES_URL',
        'https://raw.githubusercontent.com/coollabsio/coolify/main/templates/service-templates.json'
    ),

    /** عدد بطاقات الكتالوج في كل صفحة */
    'per_page' => (int) env('COOLIFY_CATALOG_PER_PAGE', 48),

    'categories' => [
        'database' => 'قواعد البيانات',
        'service' => 'خدمات جاهزة',
        'application' => 'تطبيقات',
        'custom' => 'مخصص',
    ],

    'items' => [
        // --- Databases ---
        [
            'slug' => 'db-postgresql',
            'category' => 'database',
            'coolify_key' => 'postgresql',
            'name_ar' => 'PostgreSQL',
            'description_ar' => 'قاعدة بيانات علائقية متقدمة، مناسبة للتطبيقات والمواقع الكبيرة.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => true,
            'sort_order' => 10,
            'requirements' => ['سيرفر Coolify متصل', 'مشروع وبيئة (مثل production)'],
            'install_steps' => [
                'اختر المشروع والسيرفر والبيئة.',
                'حدّد اسماً للمورد (مثال: postgres-main).',
                'اضغط إنشاء وانتظر حتى يصبح الحالة running.',
            ],
            'docs_url' => 'https://coolify.io/docs/databases/postgresql',
        ],
        [
            'slug' => 'db-mysql',
            'category' => 'database',
            'coolify_key' => 'mysql',
            'name_ar' => 'MySQL',
            'description_ar' => 'قاعدة بيانات علائقية شائعة لمواقع WordPress وتطبيقات الويب.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => true,
            'sort_order' => 11,
            'requirements' => ['سيرفر Coolify متصل', 'مشروع وبيئة'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'سمِّ المورد واضغط إنشاء.', 'استخدم بيانات الاتصال من صفحة التفاصيل.'],
            'docs_url' => 'https://coolify.io/docs/databases/mysql',
        ],
        [
            'slug' => 'db-mariadb',
            'category' => 'database',
            'coolify_key' => 'mariadb',
            'name_ar' => 'MariaDB',
            'description_ar' => 'فرع متوافق مع MySQL، خفيف وسريع.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 12,
            'requirements' => ['سيرفر Coolify متصل'],
            'install_steps' => ['اختر المشروع والسيرفر والبيئة.', 'أنشئ المورد وانتظر التشغيل.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'db-mongodb',
            'category' => 'database',
            'coolify_key' => 'mongodb',
            'name_ar' => 'MongoDB',
            'description_ar' => 'قاعدة بيانات وثائقية NoSQL.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 13,
            'requirements' => ['سيرفر Coolify متصل'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'حدّد الاسم واضغط إنشاء.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'db-redis',
            'category' => 'database',
            'coolify_key' => 'redis',
            'name_ar' => 'Redis',
            'description_ar' => 'مخزن بيانات في الذاكرة للتخزين المؤقت والطوابير.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 14,
            'requirements' => ['سيرفر Coolify متصل'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ Redis وانسخ رابط الاتصال.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'db-keydb',
            'category' => 'database',
            'coolify_key' => 'keydb',
            'name_ar' => 'KeyDB',
            'description_ar' => 'بديل عالي الأداء متوافق مع Redis.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 15,
            'requirements' => ['سيرفر Coolify متصل'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ المورد.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'db-clickhouse',
            'category' => 'database',
            'coolify_key' => 'clickhouse',
            'name_ar' => 'ClickHouse',
            'description_ar' => 'قاعدة تحليلات عمودية للبيانات الضخمة.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 16,
            'requirements' => ['سيرفر Coolify متصل'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ ClickHouse.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'db-dragonfly',
            'category' => 'database',
            'coolify_key' => 'dragonfly',
            'name_ar' => 'Dragonfly',
            'description_ar' => 'بديل Redis عالي الأداء.',
            'icon' => 'fe-database',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 17,
            'requirements' => ['سيرفر Coolify متصل'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ Dragonfly.'],
            'docs_url' => null,
        ],

        // --- One-click services (featured) ---
        [
            'slug' => 'svc-wordpress',
            'category' => 'service',
            'coolify_key' => 'wordpress-with-mariadb',
            'name_ar' => 'WordPress',
            'description_ar' => 'نظام إدارة محتوى لمواقع الشركات والمدونات والمتاجر.',
            'icon' => 'fe-globe',
            'enabled' => true,
            'featured' => true,
            'sort_order' => 100,
            'requirements' => ['سيرفر Coolify', 'نطاق أو DNS اختياري'],
            'install_steps' => [
                'اختر المشروع والسيرفر والبيئة production.',
                'سمِّ الخدمة (مثال: wordpress-blog).',
                'بعد الإنشاء افتح الخدمة في Coolify لربط النطاق وإدارة الحاويات.',
            ],
            'docs_url' => 'https://coolify.io/docs/services/wordpress',
        ],
        [
            'slug' => 'svc-ghost',
            'category' => 'service',
            'coolify_key' => 'ghost',
            'name_ar' => 'Ghost',
            'description_ar' => 'منصة نشر ومدونة احترافية.',
            'icon' => 'fe-book-open',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 101,
            'requirements' => ['سيرفر Coolify'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ الخدمة وانتظر التشغيل.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'svc-n8n',
            'category' => 'service',
            'coolify_key' => 'n8n',
            'name_ar' => 'n8n',
            'description_ar' => 'أتمتة سير العمل بدون كود.',
            'icon' => 'fe-git-branch',
            'enabled' => true,
            'featured' => true,
            'sort_order' => 102,
            'requirements' => ['سيرفر Coolify'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ n8n وافتح الواجهة من Coolify.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'svc-appwrite',
            'category' => 'service',
            'coolify_key' => 'appwrite',
            'name_ar' => 'Appwrite',
            'description_ar' => 'منصة Backend-as-a-Service للتطبيقات.',
            'icon' => 'fe-box',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 103,
            'requirements' => ['سيرفر Coolify'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أنشئ Appwrite.'],
            'docs_url' => null,
        ],

        // --- Applications ---
        [
            'slug' => 'app-public',
            'category' => 'application',
            'coolify_key' => 'public',
            'name_ar' => 'تطبيق عام (Git عام)',
            'description_ar' => 'نشر من مستودع Git عام بدون مفاتيح خاصة.',
            'icon' => 'fe-github',
            'enabled' => true,
            'featured' => true,
            'sort_order' => 200,
            'requirements' => ['مستودع Git عام', 'سيرفر Coolify'],
            'install_steps' => [
                'من معالج التثبيت ستُوجَّه لنموذج التطبيق الكامل.',
                'أدخل رابط المستودع والفرع والنطاق.',
                'اضغط نشر من صفحة التطبيق.',
            ],
            'docs_url' => 'https://coolify.io/docs/applications',
        ],
        [
            'slug' => 'app-private-github',
            'category' => 'application',
            'coolify_key' => 'private-github',
            'name_ar' => 'تطبيق GitHub خاص',
            'description_ar' => 'نشر من مستودع خاص عبر تطبيق GitHub مربوط في Coolify.',
            'icon' => 'fe-github',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 201,
            'requirements' => ['GitHub App مُعد في Coolify', 'سيرفر متصل'],
            'install_steps' => ['اربط GitHub App من Coolify أولاً.', 'أكمل النموذج من صفحة إنشاء التطبيق.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'app-private-key',
            'category' => 'application',
            'coolify_key' => 'private-key',
            'name_ar' => 'تطبيق بمفتاح نشر',
            'description_ar' => 'نشر من مستودع خاص باستخدام Deploy Key.',
            'icon' => 'fe-key',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 202,
            'requirements' => ['مفتاح خاص مُسجّل في Coolify'],
            'install_steps' => ['أضف Private Key في Coolify.', 'أكمل إنشاء التطبيق من النموذج الموسّع.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'app-dockerfile',
            'category' => 'application',
            'coolify_key' => 'dockerfile',
            'name_ar' => 'تطبيق Dockerfile',
            'description_ar' => 'بناء وتشغيل من Dockerfile في المستودع.',
            'icon' => 'fe-file-text',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 203,
            'requirements' => ['مستودع يحتوي Dockerfile'],
            'install_steps' => ['اختر المشروع والسيرفر من المعالج.', 'أكمل الحقول في نموذج التطبيق.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'app-docker-image',
            'category' => 'application',
            'coolify_key' => 'docker-image',
            'name_ar' => 'صورة Docker جاهزة',
            'description_ar' => 'تشغيل صورة من Docker Hub أو سجل خاص.',
            'icon' => 'fe-package',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 204,
            'requirements' => ['اسم الصورة والوسم (tag)'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'أدخل docker_registry_image_name و tag.'],
            'docs_url' => null,
        ],
        [
            'slug' => 'app-docker-compose',
            'category' => 'application',
            'coolify_key' => 'docker-compose',
            'name_ar' => 'Docker Compose',
            'description_ar' => 'نشر مكدس كامل من ملف docker-compose.',
            'icon' => 'fe-layers',
            'enabled' => true,
            'featured' => false,
            'sort_order' => 205,
            'requirements' => ['ملف docker-compose صالح'],
            'install_steps' => ['اختر المشروع والسيرفر.', 'الصق أو ارفع docker-compose من النموذج.'],
            'docs_url' => null,
        ],
    ],
];
