<?php

return [

    'action_labels' => [
        'refresh_info' => 'تحديث معلومات WordPress',
        'diagnose' => 'تشخيص اتصال CyberPanel',
        'plugin_activate' => 'تفعيل إضافة',
        'plugin_deactivate' => 'إيقاف إضافة',
        'plugin_update' => 'تحديث إضافة',
        'plugin_update_all' => 'تحديث كل الإضافات',
        'plugin_delete' => 'حذف إضافة',
        'theme_activate' => 'تفعيل قالب',
        'theme_deactivate' => 'إيقاف قالب',
        'theme_update' => 'تحديث قالب',
        'theme_update_all' => 'تحديث كل القوالب',
        'theme_delete' => 'حذف قالب',
        'maintenance_activate' => 'تفعيل وضع الصيانة',
        'maintenance_deactivate' => 'إيقاف وضع الصيانة',
        'debugging_on' => 'تفعيل وضع التصحيح',
        'debugging_off' => 'إيقاف وضع التصحيح',
        'lscache_on' => 'تفعيل LiteSpeed Cache',
        'lscache_off' => 'إيقاف LiteSpeed Cache',
        'search_index_on' => 'تفعيل فهرسة محركات البحث',
        'search_index_off' => 'إيقاف فهرسة محركات البحث',
        'save_auto_updates' => 'حفظ سياسات التحديث التلقائي',
        'core_reinstall' => 'إعادة تثبيت ملفات WordPress',
        'backup_create' => 'إنشاء نسخة احتياطية',
        'backup_list' => 'جلب النسخ الاحتياطية',
        'backup_delete' => 'حذف نسخة احتياطية',
        'backup_restore' => 'استعادة نسخة احتياطية',
        'user_create' => 'إنشاء مستخدم WordPress',
        'user_reset_password' => 'تغيير كلمة مرور مستخدم',
        'user_update_role' => 'تغيير دور مستخدم',
        'user_delete' => 'حذف مستخدم WordPress',
    ],

    'auto_update_policies' => [
        'wp_core' => [
            'Disabled' => 'معطّل',
            'Minor and Security Updates' => 'تحديثات أمنية وثانوية',
            'Enabled' => 'مفعّل بالكامل',
        ],
        'plugins_themes' => [
            'Disabled' => 'معطّل',
            'Enabled' => 'مفعّل',
        ],
    ],

    'actions' => [
        'refresh_info' => ['type' => 'internal'],
        'diagnose' => ['type' => 'internal'],
        'plugin_activate' => ['type' => 'api', 'method' => 'toggleWpExtension', 'extension' => 'plugin'],
        'plugin_deactivate' => ['type' => 'api', 'method' => 'toggleWpExtension', 'extension' => 'plugin'],
        'plugin_update' => ['type' => 'api', 'method' => 'updateWpPlugins'],
        'plugin_update_all' => ['type' => 'api', 'method' => 'updateWpPlugins', 'all' => true],
        'plugin_delete' => ['type' => 'api', 'method' => 'deleteWpPlugins'],
        'theme_activate' => ['type' => 'api', 'method' => 'toggleWpExtension', 'extension' => 'theme'],
        'theme_deactivate' => ['type' => 'api', 'method' => 'toggleWpExtension', 'extension' => 'theme'],
        'theme_update' => ['type' => 'api', 'method' => 'updateWpThemes'],
        'theme_update_all' => ['type' => 'api', 'method' => 'updateWpThemes', 'all' => true],
        'theme_delete' => ['type' => 'api', 'method' => 'deleteWpThemes'],
        'maintenance_activate' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'maintenanceMode', 'value' => true],
        'maintenance_deactivate' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'maintenanceMode', 'value' => false],
        'debugging_on' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'debugging', 'value' => true],
        'debugging_off' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'debugging', 'value' => false],
        'lscache_on' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'lscache', 'value' => true],
        'lscache_off' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'lscache', 'value' => false],
        'search_index_on' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'searchIndex', 'value' => true],
        'search_index_off' => ['type' => 'api', 'method' => 'updateWpSetting', 'setting' => 'searchIndex', 'value' => false],
        'save_auto_updates' => ['type' => 'api', 'method' => 'saveWpAutoUpdateSettings'],
        'core_reinstall' => ['type' => 'api', 'method' => 'reinstallWpCore'],
        'backup_create' => ['type' => 'api', 'method' => 'createWpBackup'],
        'backup_list' => ['type' => 'api', 'method' => 'listWpBackups'],
        'backup_delete' => ['type' => 'api', 'method' => 'deleteWpBackup'],
        'backup_restore' => ['type' => 'api', 'method' => 'restoreWpBackup'],
        'user_create' => ['type' => 'user'],
        'user_reset_password' => ['type' => 'user'],
        'user_update_role' => ['type' => 'user'],
        'user_delete' => ['type' => 'user'],
    ],

    'management_log_limit' => 80,

];
